import logging

LOGS_DIRECTORY = "logs"
LOGS_FULL_PATH = f"{LOGS_DIRECTORY}/twitter_service_"
CSVS_DIRECTORY = "csvs"
TWEETS_CSV_NAME = "tweets_"
TWEETS_SEARCH_PAGES = 30
TWEETS_SEARCH_WAIT_TIME = 30
TWITTER_SESSION = "session"
LOGGING_LEVEL = logging.DEBUG
DATE_CHUNK_DAYS = 2
